global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend-local"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "backend-staging"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["mlops-backend-staging.onrender.com"]

  - job_name: "backend-production"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["mlops-backend-production.onrender.com"]